name: ChestTerminal
version: ${project.version}
author: TheBusyBiscuit
description: 黏液科技附加 箱子終端 繁體翻譯版.
website: https://github.com/TheBusyBiscuit/ChestTerminal

api-version: 1.14
main: io.github.thebusybiscuit.chestterminal.ChestTerminal

depend:
- Slimefun