name: ChestTerminal
version: ${project.version}
author: TheBusyBiscuit
description: 黏液科技附加 箱子終端 繁體翻譯版.
depend: [Slimefun]

api-version: 1.13

main: io.github.thebusybiscuit.chestterminal.ChestTerminal
