name: ChestTerminal
version: ${project.version}
author: TheBusyBiscuit
description: 此插件為繁體翻譯版, 原作者"TheBusyBiscuit".
depend: [Slimefun]

api-version: 1.13

main: io.github.thebusybiscuit.chestterminal.ChestTerminal
